name: cron
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  objectbox_generator: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
